const AUTHENTICATE_ROUTE = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  WELCOME_SCREEN: 'WELCOME_SCREEN',
};

const APP_TAP = {
  MAIN_TAB: 'MAIN_TAB',
  NOTIFICATION_HAVE_EMAIL: 'NOTIFICATION_HAVE_EMAIL',
};
export {AUTHENTICATE_ROUTE, APP_TAP};
